### ISSUE TITLE
두더지 퐁퐁

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#10]
```yaml
게임 만들어줘.

title: "두더지 퐁퐁"

background:
  value: "#121212"

overlay:
  content: "화면 상단에 점수와 최고기록, 남은 시간을 표시해주세요"
  style:
    fontSize: "20px"
    color: "#FFFFFF"
    backgroundColor: "transparent"

game_rules:
  description: |
    제한 시간 30초 동안 무작위로 나타나는 두더지를 클릭하세요.
    두더지는 3x3 배경의 한 구역에 등장합니다.
    두더지를 클릭하면 점수가 올라가고, 클릭하지 못하면 사라집니다.
    두더지는 1초마다 새로운 위치에서 나타나며 한 번만 클릭 가능합니다.
    게임이 끝나면 화면 가운데 점수판이 표시되고, 상단에 최종 점수와 최고기록이 표시됩니다.
  win_condition: "30초 동안 15점 이상 획득 시 승리"
  lose_condition: "30초 동안 15점 미만이면 패배"
  control: "마우스 클릭 또는 터치로 두더지를 잡으세요."

screen_size: "모바일에서도 작동 가능하도록 화면 크기 작게"

options:
  buttons:
    - label: "시작"
      action: "게임을 시작합니다. 타이머가 작동하고 두더지가 나타나기 시작합니다."
    - label: "일시정지"
      action: "현재 게임을 일시 정지합니다. 타이머와 애니메이션이 멈춥니다."
    - label: "초기화"
      action: "게임을 재시작합니다. 점수, 타이머, 두더지 위치 등이 초기화됩니다."

framework: "어떤 Framework 도 필요하지 않은 순수 HTML, JS, CSS 로만 만들어야 하고 하나의 HTML 파일로 생성되야 합니다.
```
