### ISSUE TITLE
도망쳐! 점프볼

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#11]
```yaml
게임 만들어줘.

title: "도망쳐! 점프볼"

background:
  value: "#121212"

overlay:
  content: "화면 상단에 생존 시간과 최고기록(초)을 표시해주세요"
  style:
    fontSize: "20px"
    color: "#FFFFFF"
    backgroundColor: "transparent"

game_rules:
  description: |
    자동으로 좌우로 이동하는 공(플레이어)을 조작하여,
    다가오는 장애물(벽)을 피해 가능한 한 오래 살아남으세요.
    화면 아무곳을 클릭하거나 터치하면 공이 위로 점프합니다.
    처음 점프하게 되면 게임이 시작되고 벽이 오른쪽에서 왼쪽으로 다가옵니다.
    공은 화면 왼쪽에서 위/아래로 점프하며 벽이 오른쪽에서 왼쪽으로 다가옵니다.
    장애물은 랜덤한 간격으로 생성되며, 높이는 공의 점프 높이의 절반 이하로 랜덤하게 정해집니다.
    충돌 시 게임이 종료됩니다.
    점프는 공중 1회만 가능하며, 바닥에 닿으면 다시 점프할 수 있습니다.
    최고 생존 시간을 기준으로 기록이 저장됩니다.
    패배 시 화면 오버레이 가운데에 점수와 "재시도" 버튼이 표시됩니다.
  win_condition: "30초 이상 생존하면 승리 메시지 표시"
  lose_condition: "장애물에 충돌 시 즉시 패배"
  control: "클릭 또는 터치로 점프. 자동 이동"

screen_size: "모바일에서도 작동 가능하도록 화면 높이와 너비를 작게 정사각형으로"

options:
  buttons:
    - label: "재시도"
      action: "게임오버 후 게임을 다시 시도합니다. 시간, 장애물, 공의 위치가 초기화되고 시작버튼과 동일하게 동작합니다."

framework: "어떤 Framework 도 필요하지 않은 순수 HTML, JS, CSS 로만 만들어야 하고 하나의 HTML 파일로 생성되야 합니다.
```
