### ISSUE TITLE
미니 타워디펜스

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#12]
```yaml
게임 만들어줘.

title: "미니 타워디펜스"

background:
  value: "#121212"

overlay:
  content: "화면 상단에 라운드(라운드), 체력(HP), 골드(₲), 최고 라운드(최고)를 표시해주세요"
  style:
    fontSize: "18px"
    color: "#FFFFFF"
    backgroundColor: "transparent"

game_rules:
  description: |
    플레이어는 화면 경로 주변에 포탑을 설치하여 적 유닛의 진입을 막아야 합니다.
    적은 일정 간격으로 오른쪽에서 왼쪽으로 이동하며,
    도착 지점까지 도달하면 플레이어의 체력이 깎입니다.
    포탑은 클릭으로 설치하고, 자동으로 근처 적을 공격합니다.
    적을 처치하면 10 골드를 획득하며, 30 골드로 새로운 포탑을 설치할 수 있습니다.
    게임 시작시 60 골드를 갖고 있습니다.
    게임은 10라운드로 구성되며, 라운드가 지날수록 적이 강해져서 라운드 수 만큼 공격을 받아야 파괴됩니다.
    게임 오버 또는 클리어 시 메시지가 표시됩니다.
  win_condition: "10라운드 생존 시 승리"
  lose_condition: "체력이 0이 되면 패배"
  control: |
    - 화면 아래 포탑 버튼을 누른 뒤, 설치 가능한 위치(격자 칸)를 터치해 포탑을 설치합니다.
    - 포탑은 자동으로 사거리 내 적을 추적해 공격합니다.

screen_size: "모바일에서도 작동 가능하도록 화면 크기 작게"

options:
  buttons:
    - label: "시작"
      action: "게임을 시작하고 적이 1라운드부터 출현합니다."
    - label: "일시정지"
      action: "게임을 일시 정지합니다. 모든 움직임과 공격이 멈춥니다."
    - label: "초기화"
      action: "게임을 초기 상태로 재시작합니다. 포탑, 골드, 체력, 라운드 등이 초기화됩니다."

framework: "어떤 Framework 도 필요하지 않은 순수 HTML, JS, CSS 로만 만들어야 하고 하나의 HTML 파일로 생성되야 합니다.
```
