### ISSUE TITLE
반사신경 테스트

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#14]
```yaml
게임 만들어줘.
title: "반사신경 테스트"

background:
  value: "#000000"  # 검정 배경

overlay:
  content: "화면 상단에 반응 시간(최단/최근/평균)과 시도 횟수를 표시해주세요"
  style:
    fontSize: "18px"
    color: "#FFFFFF"
    backgroundColor: "transparent"

game_rules:
  description: |
    화면이 갑자기 초록색으로 바뀌면 즉시 클릭해야 합니다.
    초록색이 되기 전에 클릭하면 페널티가 적용됩니다.
    총 5번의 시도 중 가장 빠른 반응 시간을 기록하세요.
    배경은 어두운 색으로 유지되며, 초록색으로 바뀌는 순간이 랜덤입니다.
    랜덤시간은 2~5초 안에서 결정됩니다.
    1. 검은 화면 가운데 "게임을 시작하려면 화면을 클릭하세요. 1/5"
    2. 화면을 클릭하면 랜덤 타이머 2~5초 시작.
    3. 타이머가 완료되면 화면이 녹색으로 변하고 "클릭하세요"
    4. 클릭하면 화면이 검은색으로 변하고 기록 표시 "반응시간 xxxx ms\n다시 시작하세요. 2/5"
    5. 다시 2번 랜덤 타이머 시작
    6. 총 5회를 마무리하면 "반응시간 최소 xxxx ms/평균 xxxx ms" 표시하고 1번으로 돌아감
  win_condition: "승리 없음. 최단/평균기록을 줄이는것을 목표로 합니다."
  lose_condition: "패배 없음. 최단/평균기록을 줄이는것을 목표로 합니다."
  control: "화면이 초록색으로 바뀌는 순간 마우스를 클릭하세요."

screen_size: "모바일에서도 작동 가능하도록 화면 크기 작게"

options:
  buttons:
    - label: "시작"
      action: "게임을 시작합니다. 몇 초 후 화면 색상이 무작위로 바뀝니다."
      position: "화면 전체가 버튼입니다. 화면 아무곳이나 누르면 게임이 시작됩니다."
    - label: "초기화"
      action: "게임을 재시작합니다. 반응 시간과 시도 횟수가 초기화됩니다."
      position: "게임화면 아래"

framework: "어떤 Framework 도 필요하지 않은 순수 HTML, JS, CSS 로만 만들어야 하고 하나의 HTML 파일로 생성되야 합니다.

```
