### ISSUE TITLE
Game Generation Prompt Template

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#6]
```yaml
게임 만들어줘.
title: "게임 제목"

background:
  value: "#121212"  # 예: 색상 코드 또는 색상 설명 ("검정")

overlay:
  content: "화면 상단에 점수와 최고기록을 표시해주세요"
  style: # 필수는 아님. content 에 글로 작성해도 무방.
    fontSize: "20px"
    color: "#FFFFFF"
    backgroundColor: "transparent"

game_rules:
  description: | # 게임 규칙을 꼼꼼하게 작성.
    플레이어는 제한 시간 안에 최대한 많은 별을 클릭해야 합니다.
    별을 클릭하면 점수가 올라가고, 시간은 줄어듭니다.
    배경은 어두운 우주 이미지로, 별은 랜덤한 위치에 나타납니다.
  win_condition: "30초 내 20점 이상 획득 시 승리"
  lose_condition: "30초 내 20점 미만일 경우 패배"
  control: "마우스로 별을 클릭하여 점수를 획득합니다."

screen_size: "모바일에서도 작동 가능하도록 화면 크기 작게" # ★ 이 내용은 수정하지 마세요.

options:
  buttons:
    - label: "시작"
      action: "게임을 시작합니다. 타이머가 작동하고 별이 나타나기 시작합니다."
    - label: "일시정지"
      action: "현재 게임을 일시 정지합니다. 타이머와 애니메이션이 멈춥니다."
    - label: "초기화"
      action: "게임을 재시작합니다. 점수, 타이머, 별의 위치 등이 초기화됩니다."

framework: "어떤 Framework 도 필요하지 않은 순수 HTML, JS, CSS 로만 만들어야 하고 하나의 HTML 파일로 생성되야 합니다.
```
