### ISSUE TITLE
타이밍

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/webgame-platform#9]
```yaml
타이밍 게임 만들어줘.
title: "타이밍"

background:
  value: "검정"

overlay:
  content: "화면 상단에 흰색 작은 글씨로 점수와 최고기록을 표시해주세요. Score: 0.00s, Best: 0.00s"
game_rules:
  description: |
    플레이어는 최대한 정확한 시간에 화면을 아무곳이나 클릭/터치해야 합니다.
    게임 진행순서는 아래와 같습니다.
    1. 먼저 화면 가운데 "60초 카운트다운" 버튼 이 표시됩니다.
    2. 버튼을 클릭/터치하면 버튼이 사라집니다.
    3. 내부적으로 타이머가 흐릅니다. 흐르는 시간은 표시하지 않습니다.
    4. 60초가 지나면 배경화면이 붉은색으로 바뀌고 크고 흰 타임오버 글씨가 가운데 표시됩니다. 화면을 아무곳이나 터치하면 1로 돌아갑니다.
    5. 화면을 클릭/터치하면 지속된 시간을 초 단위로 표시하고 이 초 단위 시간이 점수가 됨. "60초 다시하기" 버튼이 나타남. 버튼을 클릭/터치하면 1로 돌아갑니다. 내부타이머는 중지합니다.
  win_condition: "60초에 가까우면 좋은 것"
  lose_condition: "60초를 넘기면 타임오버"
  control: "화면을 클릭/터치"

screen_size: "모바일에서도 작동 가능하도록 화면 크기 작게" 

framework: "어떤 프레임워크도 없이 순수 HTML/Javascript/CSS 만 사용합니다."

options:
  buttons:
    - label: "60초 카운트다운"
      action: "타이머가 시작됩니다. 시작 후에는 사라집니다."
      size: 화면을 50% 채울 정도로 크게
    - label: "60초 다시하기"
      action: "빈화면을 터치하면 나타납니다. 누르면 사라집니다."
      size: 화면을 50% 채울 정도로 크게 (카운트다운 버튼과 동일)

```
